export const BASEURL = 'https://api-gate2.movieglu.com/'
export const CLIENT = 'ADRO'
export const X_API_KEY = 'JtwQcG7tjK1NC5dM8ilpi1ADb3ELkOf8afnhpq0j'
export const AUTHOURIZATION = 'Basic QURSTzpNZ21Wdm43bEFtMFY='
export const API_VERSION = 'v200'
export const LOCALURL = 'http://backend.locatecinema.com/api/auth/'
export const GOOGLE_MAPS_APIKEY = 'AIzaSyC8YNvVgE9bLa-Xt2zqCQ4vI2G8XrreOEk'